config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "users/registrations"}
  get "/home", to: "static_pages#home"
  root "static_pages#home"
  resources :movies, only: %i(index show)
  resources :tv_shows, only: %i(index show) do
    resources :seasons, only: :show do
      resources :episodes, only: :show
    end
  end
  resources :users
  resources :celebrities, only: %i(index show)
  resources :news
  resources :reviews, only: %i(create destroy)
  resources :search, only: :index

  namespace :admin do
    resources :movies
    resources :users, except: %i(new create edit)
    resources :tv_shows do
      resources :seasons, except: :index do
        resources :episodes, except: :index
      end
    end
    resources :news, except: %i(new create edit)
    resources :celebrities
    resources :celebrity_media, only: %i(create destroy)
    resources :requests, only: %i(index update destroy)
    root "dashboard#index"
  end
  resources :requests, only: :create
end

app/models/season.rb
class Season < ApplicationRecord
  belongs_to :tv_show
  has_many :episodes, dependent: :destroy

  mount_uploader :poster, SeasonPosterUploader

  ATTR = %i(info poster season_number).freeze

  validates :info, presence: true,
            length: {maximum: Settings.seasons.info_max_length}
  validate :unique_season_number

  celebrities_list = lambda do |season_id|
    Celebrity.where(id: includes(episodes: [medium: [celebrity_media: :celebrity]]).where(id: season_id)
                            .pluck("celebrities.id").uniq)
  end
  scope :celebrities_list, celebrities_list

  def score user_role
    arr = episodes.map{|e| e.score(user_role)}.reject(&:zero?)
    return 0 if arr.empty?
    arr.reduce(:+) / arr.size
  end

  def load_release_year
    date = episodes.where("episodes.episode_number = 1").pluck("episodes.release_date")
    year = date[0]
  end

  def load_director
    director = episodes.joins(medium: [celebrity_media: :celebrity]).where("celebrity_media.role = 1").pluck("celebrities.name").uniq
    return director unless director.empty?
  end

  private

  def unique_season_number
    return unless tv_show.seasons.where(season_number: season_number).exists?
    errors.add :season_number, I18n.t("admin.seasons.duplicate")
  end
end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < Admin::BaseController
  before_action :load_tvshow
  before_action :load_season, only: %i(show edit update destroy)

  def new
    @season = @tv_show.seasons.new
  end

  def show; end

  def edit; end

  def create
    @season = @tv_show.seasons.new season_params

    if @season.save
      flash[:success] = t ".create_success"
      redirect_to [:admin, @tv_show, @season]
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def update
    if @season.update_attributes season_params
      flash[:success] = t ".update_success"
      redirect_to [:admin, @tv_show, @season]
    else
      flash[:danger] = t ".update_failed"
      render :edit
    end
  end

  def destroy
    @season.destroy
    flash[:notice] = t ".delete_success"
    redirect_to [:admin, @tv_show]
  end

  private

  def season_params
    params.require(:season).permit Season::ATTR
  end

  def load_tvshow
    @tv_show = TvShow.find_by id: params[:tv_show_id]

    return if @tv_show
    flash[:danger] = t ".not_found"
    redirect_to admin_tv_shows_url
  end

  def load_season
    @season = @tv_show.seasons.find_by id: params[:id]

    return if @season
    flash[:danger] = t ".not_found"
    redirect_to admin_tv_show_url @tv_show
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  before_action :build_movie_tvshow, only: :show
  def show
    @user = User.new
    @tv_show = TvShow.find_by id: params[:tv_show_id]
    @season = Season.find_by id: params[:id]

    @critic_score = @season.score :critic
    @audience_score = @season.score :normal

    @celebrities = Season.celebrities_list @season.id
  end

  private

  def build_movie_tvshow
    @top_score_movie = Movie.create_top_score
    @top_score_movie_tab = @top_score_movie.take Settings.tab_show

    @top_score_tvshow = TvShow.create_top_score
    @top_score_tvshow_tab = @top_score_tvshow.take Settings.tab_show
  end
end

app/views/admin/seasons/_form.html.erb
<%= form_for [:admin, @tv_show, season] do |f| %>
  <%= render "admin/shared/error_messages", object: f.object %>
    <h4 class="text-warning"><%= f.label :season_number %></h4>
    <%= f.number_field :season_number, class: "form-control" %>
    <br>

    <h4 class="text-warning"><%= f.label :info %></h4>
    <%= f.text_area :info, class: "form-control" %>
    <br>
    <%= f.submit t("submit"), class: "btn btn-primary" %>
<% end %>

app/views/admin/seasons/_season.html.erb
<h3><%= t ".edit" %>
  <%= link_to season.season_number, admin_tv_show_season_path(@tv_show, season), class: "text-danger" %>
</h3>
<span class="badge badge-warning">
  <%= link_to t(".delete"), admin_tv_show_season_path(@tv_show,season), method: :delete, data: {confirm: t(".sure")} %>
</span>
<br><br>
<div class="box">
  <div class="box-body">
    <%= render "admin/seasons/form", season: season %>
  </div>
</div>
<br>

app/views/admin/seasons/edit.html.erb
<p><%= t ".edit" %><%= @season.season_number %></p>

<%= render "admin/seasons/form", season: @season %>

app/views/admin/seasons/new.html.erb
<h1><%= t ".new" %></h1>

<%= render "form", season: @season %>

app/views/admin/seasons/show.html.erb
<div class="box">
  <div class="box-body">
    <h3 class="text-center"><%= t ".Season" %>
      <span class="text-danger"><%= @season.season_number %></span>
    </h3>
    <span class="badge badge-danger">
      <%= link_to t(".back"), admin_tv_show_path(@tv_show) %>
    </span>
    <span class="badge badge-primary">
      <%= link_to t(".edit"), edit_admin_tv_show_season_path(@season) %>
    </span>
    <br><br>
    <%= @season.info %>
  </div>
</div>

<% if @season.episodes.any? %>
  <br>
  <%= render @season.episodes %>
<% end %>

<h2><%= t ".add_episode" %></h2>
<%= render "admin/episodes/form", episode: @season.episodes.build %>
<br>

<span class="badge badge-danger">
  <%= link_to t(".back"), admin_tv_show_path(@tv_show) %>
</span>