config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "users/registrations"}
  get "/home", to: "static_pages#home"
  root "static_pages#home"
  resources :movies, only: %i(index show)
  resources :tv_shows, only: %i(index show) do
    resources :seasons, only: :show do
      resources :episodes, only: :show
    end
  end
  resources :users
  resources :celebrities, only: %i(index show)
  resources :news
  resources :reviews, only: %i(create destroy)
  resources :search, only: :index

  namespace :admin do
    resources :movies
    resources :users, except: %i(new create edit)
    resources :tv_shows do
      resources :seasons, except: :index do
        resources :episodes, except: :index
      end
    end
    resources :news, except: %i(new create edit)
    resources :celebrities
    resources :celebrity_media, only: %i(create destroy)
    resources :requests, only: %i(index update destroy)
    root "dashboard#index"
  end
  resources :requests, only: :create
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < Admin::BaseController
  before_action :load_movie, except: %i(index new create)

  def index
    @movies = Movie.create_desc.page(params[:page]).per Settings.paginate
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new movie_params

    if @movie.save
      flash[:success] = t ".create_success"
      redirect_to admin_movie_path(@movie)
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @movie.update_attributes movie_params
      flash[:success] = t ".update_success"
      redirect_to admin_movie_path(@movie)
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  def destroy
    @movie.destroy
    flash[:success] = t ".delete_success"
    redirect_to admin_movies_url
  end

  private

  def movie_params
    params.require(:movie).permit Movie::ATTR
  end

  def load_movie
    @movie = Movie.find_by id: params[:id]

    return if @movie
    flash[:danger] = t ".not_found"
    redirect_to admin_movies_url
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include ReviewsHelper
  before_action :load_movie, only: :show
  before_action :build_movie_tvshow, only: %i(index show)

  def index
    @movies = Movie.create_desc.page(params[:page]).per Settings.paginate
  end

  def show
    @review = Review.new

    @critic_score = @movie.score(:critic)
    @audience_score = @movie.score(:normal)
    @celebrities = Movie.celebrities_list @movie.id
  end

  private

  def load_movie
    @movie = Movie.find_by id: params[:id]

    return if @movie
    flash[:danger] = t ".not_found"
    redirect_to movies_url
  end

  def build_movie_tvshow
    @top_score_movie = Movie.create_top_score
    @top_score_movie_tab = @top_score_movie.take Settings.tab_show

    @top_score_tvshow = TvShow.create_top_score
    @top_score_tvshow_tab = @top_score_tvshow.take Settings.tab_show
  end
end

app/views/movies/_menu1.html.erb
<div class="tab-pane active" id="menu1">
  <div class="panel panel-default">
    <h2><span class="badge badge-warning">
      <%= t "movies.show.tab_movie.top" %></span></h2>
    <div>
      <% @top_score_movie_tab.each do |movie| %>
        <h5><span class="badge-light"><i class="fa fa-film" aria-hidden="true"></i></span>
          <%= link_to movie.name, movie, class: "text-warning" %>
        </h5>
      <% end %>
    </div>
    <% unless @top_score_movie.count <= 5 %>
      <%= link_to t("movies.show.more"), movies_path, class: "text-info" %>
    <% end %>
  </div>
</div>

app/views/movies/_menu2.html.erb
<div class="tab-pane fade" id="menu2">
  <div class="panel panel-default">
    <h2><span class="badge badge-warning">
      <%= t "tv_shows.show.tab_tvshow.top" %></span></h2>
    <div>
      <% @top_score_tvshow.take(Settings.tab_show).each do |tvshow| %>
        <h5><span class="badge-light"><i class="fa fa-film" aria-hidden="true"></i></span>
          <%= link_to tvshow.name, tvshow, class: "text-warning" %>
        </h5>
      <% end %>
    </div>
    <% unless @top_score_tvshow.count <= Settings.tab_show %>
      <%= link_to t("movies.show.more"), tv_shows_path, class: "text-info" %>
    <% end %>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class="trailer-single fix-margin-search">
  <div class="trailer-img">
    <%= image_tag movie.poster.url if movie.poster? %>
  </div>
  <div class="trailer-titel">
    <h5>
      <p class="badge badge-warning"> <%= movie.score(:critic).zero? ? "N/A" : movie.score(:critic).round(1) %> </p>
      <p><%= link_to (movie.name + " (" + movie.release_date.year.to_s + ")"), movie, class: "text-center" %></p>
    </h5>
  </div>
</div>

app/views/movies/index.html.erb
<%= content_for :slider do %>
  <div class="slider-area fake-slider container"></div>
<% end %>
<div class="container content-margin-top reset-padding">
<p id="notice"><%= notice %></p>
  <div class="row">
    <div class="col-9">
      <h2 class="text-danger movie_head"><%= t "section.title_moviews" %> <span><%= t "section.span_moviews"
      %></span></h2>
      <div class="row">
        <% @movies.each do |movie| %>
          <div class="col-4">
            <div class="card movie_line">
              <%= image_tag movie.poster.url, class: "card-img-top" if movie.poster? %>
              <div class="card-body item-body">
                <h4 class="card-title">
                  <span class="badge badge-warning">
                    <%= movie.score(:critic).zero? ? "N/A" : movie.score(:critic).round(1)%>
                  </span>
                  <%= link_to (movie.name + " (" + movie.release_date.year.to_s + ")"), movie %>
                </h4>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%= paginate @movies, theme: "twitter-bootstrap-4",
                   pagination_class: "pagination-sm"%>
    </div>
    <div class="col-3 reset-padding">
      <ul class="nav nav-tabs">
        <li class="nav-item tab-nav-item">
          <%= link_to t("movies.show.tab_movie.title"), "#menu1", data: {toggle: "pill"}, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to t("movies.show.tab_tvshow.title"), "#menu2", data: {toggle: "pill"}, class: "nav-link"%>
        </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <%= render "movies/menu1" %>
        <%= render "movies/menu2" %>
      </div>
    </div>
  </div>
</div>

app/views/movies/show.html.erb
<%= content_for :slider do %>
  <div class="slider-area fake-slider container"></div>
<% end %>
<div class="container content-margin-top">
  <div class="row">
    <div class="col-3 reset-padding">
      <ul class="nav nav-tabs">
        <li class="nav-item">
          <%= link_to t(".tab_movie.title"), "#menu1", data: {toggle: "pill"}, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".tab_tvshow.title"), "#menu2", data: {toggle: "pill"}, class: "nav-link" %>
        </li>
      </ul>
      <!-- Tab panes -->
      <div class="tab-content">
        <%= render "movies/menu1" %>
        <%= render "movies/menu2" %>
      </div>
    </div>
    <div class="col-9">
      <div class="row">
        <div class="col-4">
          <%= image_tag @movie.poster.url if @movie.poster? %>
        </div>
        <div class="col-8 bg-dark">
          <br>
          <div class="text-center">
            <h3 class="text-white">
              <%= @movie.name %>
              (<%= @movie.release_date.year %>)
            </h3>
            <% if @critic_score.zero? %>
              <div class="text-white">
                <%= t ".right_box.note1" %>
              </div>
              <div class="text-white">
                <%= t ".right_box.note2" %>
              </div>
            <% end %>
          </div>
          <br>
          <div class="row">
            <div class="col-6 text-right">
              <h3><span class="badge-warning badge">
                  <%= @critic_score.zero? ? "N/A" : @critic_score.round(1) %></span></h3>
              <h4 class="text-muted">
                <%= t ".right_box.tomascore" %>
              </h4>
              <p class="text-light">
                <%= t ".right_box.explain1" %>
              </p>
            </div>
            <div class="col-6">
              <h3><span class="badge-warning badge">
                  <%= @audience_score.zero? ? "N/A" : @audience_score.round(1) %></span></h3>
              <h4 class="text-muted">
                <%= t ".right_box.audiscore" %>
              </h4>
              <p class="text-light">
                <%= t ".right_box.explain2" %>
              </p>
            </div>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-4">
        </div>
        <div class="col-8">
          <% if user_signed_in? %>
            <%= render("reviews/form", medium_id: @movie.medium.id) unless reviewed?(current_user, @movie.medium) %>
          <% end %>
        </div>
      </div>
      <br><br>
      <div class="row">
        <div class="col-12">
          <h3 class="text-center bg-danger"><span class="text-white ">
              <%= t ".tab_movie.title" %></span>
            <%= t "info" %>
          </h3>
        </div>
        <div class="col-12">
          <p>
            Director:
            <% @movie.load_director.each do |d| %>
              <span class="text-light"><%= d %></span>
            <% end %>
          </p>
          <p>
            Release date: <span class="text-light"><%= I18n.l(@movie.release_date.to_time, format: :short) %></span>
          </p>
          <p>Informartion:
            <p class="text-light">
              <%= @movie.info %>
            </p>
          </p>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-12">
          <h3 class="text-center bg-danger"><span class="text-white ">
              <%= t "cast" %></span></h3>
        </div>
        <div class="col-12">
          <div class="owl-carousel celebrities-slider" style="color: white">
            <%= render @celebrities %>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-12">
          <h3 class="text-center bg-danger"><span class="text-white ">
              <%= t "review" %></span>
          </h3>
        </div>
        <% if @movie.medium.reviews.any? %>
          <%= render @movie.medium.reviews %>
        <% else %>
          <%= t ".no_review" %>
        <% end %>
      </div>
    </div>
  </div>
</div>