config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "users/registrations"}
  get "/home", to: "static_pages#home"
  root "static_pages#home"
  resources :movies, only: %i(index show)
  resources :tv_shows, only: %i(index show) do
    resources :seasons, only: :show do
      resources :episodes, only: :show
    end
  end
  resources :users
  resources :celebrities, only: %i(index show)
  resources :news
  resources :reviews, only: %i(create destroy)
  resources :search, only: :index

  namespace :admin do
    resources :movies
    resources :users, except: %i(new create edit)
    resources :tv_shows do
      resources :seasons, except: :index do
        resources :episodes, except: :index
      end
    end
    resources :news, except: %i(new create edit)
    resources :celebrities
    resources :celebrity_media, only: %i(create destroy)
    resources :requests, only: %i(index update destroy)
    root "dashboard#index"
  end
  resources :requests, only: :create
end

app/views/layouts/admin/_css.html.erb
<%= stylesheet_link_tag "admin/bootstrap.min" %>
<%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css" %>
<%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
<%= stylesheet_link_tag "admin/themify-icons" %>
<%= stylesheet_link_tag "admin/cryptocurrency-icons" %>
<%= stylesheet_link_tag "admin/plugins" %>
<%= stylesheet_link_tag "admin/helper" %>
<%= stylesheet_link_tag "admin/style" %>
<%= stylesheet_link_tag "admin/style-primary" %>

app/views/layouts/admin/_footer.html.erb
<div class="footer-section">
  <div class="container-fluid">
    <div class="footer-copyright text-center">
      <p class="text-body-light"><%= t "nameweb" %> &copy;
        <span class="badge-warning badge"><%= link_to t("nameteam"), "#"%></span>
      </p>
    </div>
  </div>
</div>

app/views/layouts/admin/_header.html.erb
<div class="header-section">
  <div class="container-fluid">
    <div class="row justify-content-between align-items-center">
      <div class="header-logo col-auto">
        <%= image_tag("home-one/icon/logo.png", class: "logo-light") %>
        <%# <%= link_to image_tag("home-one/icon/logo.png", class: "logo-light"), root_path %>
      </div>
      <div class="header-right flex-grow-1 col-auto">
        <div class="row justify-content-between align-items-center">
          <%= render "layouts/admin/search_header" %>
          <div class="col-auto">
            <ul class="header-notification-area">
              <li class="adomx-dropdown position-relative col-auto">
                <%= link_to '<i class="zmdi zmdi-caret-down drop-arrow"></i>'.html_safe, "#", class: "toggle" %>
                <ul class="adomx-dropdown-menu dropdown-menu-language">
                  <li>
                    <%= link_to t("admin_gui.language1"), "#" %>
                  </li>
                  <li>
                    <%= link_to t("admin_gui.language2"), "#" %>
                  </li>
                </ul>
              </li>
              <li>
                <ul>
                  <li>
                    <%= link_to t("Home"), root_path %>
                  </li>
                  <li>
                    <%= link_to t("logout"), destroy_user_session_path, method: :delete %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_js.html.erb
<!-- Global Vendor, plugins & Activation JS -->
<%= javascript_include_tag "admin/modernizr-3.6.0.min" %>
<%= javascript_include_tag "admin/jquery-3.3.1.min" %>
<%= javascript_include_tag "admin/popper.min" %>
<%= javascript_include_tag "admin/bootstrap.min" %>
<!--Plugins JS-->
<%= javascript_include_tag "admin/perfect-scrollbar.min" %>
<%= javascript_include_tag "admin/tippy4.min" %>
<!--Main JS-->
<%= javascript_include_tag "admin/main" %>
<!--Moment-->
<%= javascript_include_tag "admin/moment.min" %>
<!--Daterange Picker-->
<%= javascript_include_tag "admin/daterangepicker" %>
<%= javascript_include_tag "admin/daterangepicker.active" %>
<!--Echarts-->
<%= javascript_include_tag "admin/Chart.min" %>
<%= javascript_include_tag "admin/chartjs.active" %>
<!--VMap-->
<%= javascript_include_tag "admin/jquery.vmap.min" %>
<%= javascript_include_tag "admin/jquery.vmap.world" %>
<%= javascript_include_tag "admin/jquery.vmap.sampledata" %>
<%= javascript_include_tag "admin/vmap.active" %>

app/views/layouts/admin/_left_side.html.erb
<div class="side-header show">
  <button class="side-header-close"><i class="zmdi zmdi-close"></i></button>
  <div class="side-header-inner custom-scroll">
    <nav class="side-header-menu" id="side-header-menu">
      <ul>
        <li>
          <%= link_to admin_movies_path do %>
            <i class="ti-package"></i> <span><%= t ".movies" %></span>
          <% end %>
        </li>
        <li>
          <%= link_to admin_tv_shows_path do %>
            <i class="ti-palette"></i> <span><%= t ".tv_show" %></span>
          <% end %>
        </li>
        <li>
          <%= link_to admin_celebrities_path do %>
            <i class="ti-palette"></i> <span><%= t ".celebrities" %></span>
          <% end %>
        </li>
        <li>
          <%= link_to admin_news_index_path do %>
            <i class="ti-palette"></i> <span><%= t ".news" %></span>
          <% end %>
        </li>
        <li>
          <%= link_to admin_requests_path do %>
            <i class="ti-palette"></i> <span><%= t ".requests" %></span>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/admin/_search_header.html.erb
<div class="col-auto">
  <div class="row align-items-center">
    <div class="col-auto"><button class="side-header-toggle"><i class="zmdi zmdi-menu"></i></button></div>
    <div class="col-auto">
      <div class="header-search">
        <button class="header-search-open d-block d-xl-none"><i class="zmdi zmdi-search"></i></button>
        <div class="header-search-form">
          <form action="#">
            <input type="text" placeholder="Search Here">
            <button><i class="zmdi zmdi-search"></i></button>
          </form>
          <button class="header-search-close d-block d-xl-none"><i class="zmdi zmdi-close"></i></button>
        </div>
      </div>
    </div>
  </div>
</div>