config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: {registrations: "users/registrations"}
  get "/home", to: "static_pages#home"
  root "static_pages#home"
  resources :movies, only: %i(index show)
  resources :tv_shows, only: %i(index show) do
    resources :seasons, only: :show do
      resources :episodes, only: :show
    end
  end
  resources :users
  resources :celebrities, only: %i(index show)
  resources :news
  resources :reviews, only: %i(create destroy)
  resources :search, only: :index

  namespace :admin do
    resources :movies
    resources :users, except: %i(new create edit)
    resources :tv_shows do
      resources :seasons, except: :index do
        resources :episodes, except: :index
      end
    end
    resources :news, except: %i(new create edit)
    resources :celebrities
    resources :celebrity_media, only: %i(create destroy)
    resources :requests, only: %i(index update destroy)
    root "dashboard#index"
  end
  resources :requests, only: :create
end

app/models/tv_show.rb
class TvShow < ApplicationRecord
  include Search
  has_many :seasons, dependent: :destroy

  mount_uploader :poster, TvShowPosterUploader

  scope :create_desc, ->{order(created_at: :desc)}
  scope :create_top_score, ->{sort_by{|tv| [tv.score(:critic), tv.score(:normal)]}.reverse}

  scope :load_all, (
  lambda do
    joins(seasons: [episodes: [medium: [celebrity_media: :celebrity]]]).select("tv_shows.id, celebrities.name, "\
      "tv_shows.name as film_name, episodes.release_date")
  end
  )
  scope :list_search, ->(tvshows_id){find(tvshows_id)}

  scope :celebrities_list, (
  lambda do |tvshow_id|
    Celebrity.where(id: includes(seasons: [episodes: [medium: [celebrity_media: :celebrity]]]).where(id: tvshow_id)
                            .pluck("celebrities.id").uniq)
  end)

  ATTR = %i(name info poster).freeze

  validates :name, presence: true,
            length: {maximum: Settings.tvshows.name_max_length}
  validates :info, presence: true,
            length: {maximum: Settings.tvshows.info_max_length}

  def score user_role
    arr = seasons.map{|s| s.score(user_role)}.reject(&:zero?)
    return 0 if arr.empty?
    arr.reduce(:+) / arr.size
  end

  def load_release_year
    date = seasons.joins(:episodes).where("seasons.season_number = 1 AND episodes.episode_number = 1").pluck("episodes.release_date")
    return if date.empty?
    year = date[0]
  end

  def load_director
    director = seasons.joins(episodes: [medium: [celebrity_media: :celebrity]]).where("celebrity_media.role = 1").pluck("celebrities.name").uniq
    return director unless director.empty?
  end
end

app/controllers/admin/tv_shows_controller.rb
class Admin::TvShowsController < Admin::BaseController
  before_action :load_tvshow, except: %i(index new create)

  def index
    @tv_shows = TvShow.create_desc.page(params[:page]).per Settings.paginate
  end

  def new
    @tv_show = TvShow.new
  end

  def create
    @tv_show = TvShow.new tv_show_params

    if @tv_show.save
      flash[:success] = t ".create_success"
      redirect_to [:admin, @tv_show]
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @tv_show.update_attributes tv_show_params
      flash[:success] = t ".update_success"
      redirect_to [:admin, @tv_show]
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  def destroy
    if @tv_show.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to admin_tv_shows_url
  end

  private

  def tv_show_params
    params.require(:tv_show).permit TvShow::ATTR
  end

  def load_tvshow
    @tv_show = TvShow.find_by id: params[:id]

    return if @tv_show
    flash[:danger] = t ".not_found"
    redirect_to admin_tv_shows_url
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :load_tvshow, only: :show
  before_action :build_movie_tvshow, only: %i(index show)

  def index
    @tv_shows = TvShow.create_desc.page(params[:page]).per Settings.paginate
  end

  def show; end

  private

  def load_tvshow
    @tv_show = TvShow.find_by id: params[:id]

    if @tv_show
      @critic_score = @tv_show.score(:critic)
      @audience_score = @tv_show.score(:normal)
      @celebrities = TvShow.celebrities_list @tv_show.id
    else
      flash[:danger] = t ".not_found"
      redirect_to tv_shows_url
    end
  end


  def build_movie_tvshow
    @top_score_movie = Movie.create_top_score
    @top_score_movie_tab = @top_score_movie.take Settings.tab_show

    @top_score_tvshow = TvShow.all.create_top_score
    @top_score_tvshow_tab = @top_score_tvshow.take Settings.tab_show
  end
end

app/views/admin/tv_shows/_form.html.erb
<%= form_for [:admin, @tv_show] do |f| %>
  <%= render "admin/shared/error_messages", object: f.object %>

  <h4 class="text-warning"><%= f.label t ".name" %></h4>
  <%= f.text_field :name, class: "form-control" %>

  <h4 class="text-warning"><%= f.label t ".info" %></h4>
  <%= f.text_area :info, class: "form-control" %>

  <h4 class="text-warning"><%= f.label t ".poster" %></h4>
  <span class="poster">
    <%= f.file_field :poster, accept: Settings.tvshows.poster_accept %>
  </span>

  <%= f.submit t(".submit"), class: "btn btn-primary"%>
<% end %>

app/views/admin/tv_shows/edit.html.erb
<h1><%= t ".title" %></h1>

<div class="box">
  <div class="box-body">
    <%= render "form", tv_show: @tv_show %>
  </div>
</div>

app/views/admin/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= t ".title" %></h1><span class="badge badge-warning"><%= link_to t(".new"), new_admin_tv_show_path %></span>
<br>
<br>
<div class="col-12 mb-30">
  <div class="box">
    <div class="box-body">
      <div class="table-responsive">
        <table class="table table-vertical-middle table-selectable">
          <!-- Table Head Start -->
          <thead>
          <tr>
            <th><span><%= t ".id" %></span></th>
            <th><span><%= t ".image" %></span></th>
            <th><span><%= t ".name" %></span></th>
            <th><span><%= t ".action" %></span></th>
          </tr>
          </thead><!-- Table Head End -->
          <tbody>
          <% @tv_shows.each do |tv_show| %>
            <tr>
              <td>#<%= tv_show.id %></td>
              <td>
                <%= image_tag tv_show.poster.url, class: "table-product-image" if tv_show.poster? %>
              </td>
              <td><h4><%= tv_show.name %></h4></td>
              <td>
                <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, [:admin, tv_show] %>
                <%= link_to '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'.html_safe, edit_admin_tv_show_path(tv_show) %>
                <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, [:admin, tv_show], method: :delete,
                            data: {confirm: t(".sure")} %>
              </td>
            </tr>
          <% end %>
          </tbody><!-- Table Body End -->
        </table>
      </div>
    </div>
  </div>
</div>
<%= paginate @tv_shows, theme: "twitter-bootstrap-4",pagination_class: "pagination-sm" %>

app/views/admin/tv_shows/new.html.erb
<h3><%= t ".new" %></h3>

<div class="box">
  <div class="box-body">
    <%= render "form", tv_show: @tv_show %>
  </div>
</div>

app/views/admin/tv_shows/show.html.erb
<h3><%= @tv_show.name %><br></h3>
<span class="badge-warning badge"><%= link_to t(".back"), admin_tv_shows_path %></span>
<span class="badge-success badge"><%= link_to t(".edit"), edit_admin_tv_show_path(@tv_show) %></span>
<span class="badge-primary badge"><%= link_to t(".destroy"), [:admin, @tv_show], method: :delete, data: {confirm: t("
.sure")} %></span>
<br><br>
<div class="box">
  <div class="box-body">
    <%= @tv_show.info %>
    <br><br>
    <%= image_tag @tv_show.poster.url if @tv_show.poster? %><br>
  </div>
</div>

<% if @tv_show.seasons.any? %>
  <br>
  <%= render @tv_show.seasons %>
<% end %>

<div class="box">
  <div class="box-body">
    <h2><%= t ".add_season" %></h2>
    <%= render "admin/seasons/form", season: @tv_show.seasons.build %>
    <br>
  </div>
</div>